// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChxV8dYAPCdufnw30pV73DlNzXCh1Qj7k',
    appId: '1:977411301281:web:web_app_id',
    messagingSenderId: '977411301281',
    projectId: 'future14-afdbc',
    authDomain: 'future14-afdbc.firebaseapp.com',
    storageBucket: 'future14-afdbc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChxV8dYAPCdufnw30pV73DlNzXCh1Qj7k',
    appId: '1:977411301281:android:4a4616c70e3c038338f5e0',
    messagingSenderId: '977411301281',
    projectId: 'future14-afdbc',
    storageBucket: 'future14-afdbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChxV8dYAPCdufnw30pV73DlNzXCh1Qj7k',
    appId: '1:977411301281:ios:ios_app_id',
    messagingSenderId: '977411301281',
    projectId: 'future14-afdbc',
    storageBucket: 'future14-afdbc.appspot.com',
    iosClientId: 'ios_client_id.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.admintest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChxV8dYAPCdufnw30pV73DlNzXCh1Qj7k',
    appId: '1:977411301281:web:windows_app_id',
    messagingSenderId: '977411301281',
    projectId: 'future14-afdbc',
    storageBucket: 'future14-afdbc.appspot.com',
    authDomain: 'future14-afdbc.firebaseapp.com',
  );
}
